allowBuilds:
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  workerd: true
overrides:
  "@astrojs/cloudflare": $@astrojs/cloudflare
  astro: $astro
  wrangler: $wrangler
  # vite: 8.0.0
