name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - name: Instrumentation
        run: |
          pwd
          ls -l
          cat tsconfig.json
          export
          node --version
          pnpm --version
          npx tsc --version

      - name: Typecheck
        run: pnpm run types:check

      - name: Linting
        run: pnpm run lint:check

      - name: Formatting
        run: pnpm run format:check

      - name: Build
        run: |
          echo "BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}" > .env
          pnpm run build

      - name: Instrument folder
        run: |
          echo "ls -la dist/"
          ls -la dist/
          echo "cat dist/client/.assetsignore"
          cat dist/client/.assetsignore

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
