name: CI/CD

on:
  - push
  - pull_request

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
      - id: check
        shell: bash
        run: |
          message="$(git log -1 --pretty=%B)"

          echo "Commit message:"
          echo "$message"

          if [[ "$message" == "[wip]"* || "$message" == "[broken]"* ]]; then
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          fi

  build-and-deploy:
    needs: check-commit-message
    if: needs.check-commit-message.outputs.should_run == 'true'
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      cloudflare_env: staging
    secrets: inherit
